name: Trigger GitHub Action - Transformer
description: Transform the "Trigger GitHub Action" payload

inputs:
  fileKey:
    description: Figma file key
    required: true
  pageName:
    description: Page name
    required: true
  selection:
    description: Stringified array of the selected nodes (id, name)
    required: true

outputs:
  fileKey:
    description: Figma file key
  pageName:
    description: Page name
  selection:
    description: Selected nodes

runs:
  using: node16
  main: main.js
